### ISSUE TITLE
希望能在添加修改涂白判定大小功能

### ISSUE THREAD

**Issue by cyk-0** [LabelPlus/PS-Script#101]
<img width="586" alt="20210413180609" src="https://user-images.githubusercontent.com/56858958/114535772-faa91a80-9c82-11eb-9421-cb3073c17b95.png">
因为很多对话框不是完全封闭的，缝隙稍微大一点就会导致涂掉外面，希望能添加修改容差的功能

**Comment by noodlefighter** [comment]
感谢建议

**Comment by noodlefighter** [comment]
已实现
