### ISSUE TITLE
是否可以在批量嵌字时增加【字间距设置选项】

### ISSUE THREAD

**Issue by Pulaimarii** [LabelPlus/PS-Script#116]
如题，很多嵌字都会选择字间距25或者是更大的50，而脚本直接导入的默认字间距是0，目前还是靠录制动作逐个psd调整，如果能增加这个功能真的非常感谢~！

**Comment by noodlefighter** [comment]
这类格式控制, 可以直接修改默认psd模板, 与配置独立, 也方便打包分发

Pulaimarii ***@***.***> 于 2023年6月24日周六 13:59写道：

**Comment by Pulaimarii** [comment]
非常抱歉，我不太明白psd模板怎么修改，因为我是个人汉化也没有组可以请教经验，已经自己先搜索了psd修改模板等关键词，但是有太多不相关的干扰结果，大部分都是一些海报模板的获取广告……
不知道可不可以请您几句话指点一下……真的非常非常感谢！

**Comment by noodlefighter** [comment]
喔，我没说清楚，是LabelPlus的psd模板功能，参考：
https://labelplus.gitbook.io/labelplus_help/pswen-ben-dao-ru-jiao-ben-shuo-ming#wen-dang-mo-ban

**Comment by Pulaimarii** [comment]
问题已解决，再次非常感谢！
