### ISSUE TITLE
导入脚本界面改进

### ISSUE THREAD

**Issue by sgqy** [LabelPlus/PS-Script#42]
<a href="https://github.com/noodlefighter"><img src="https://avatars0.githubusercontent.com/u/5947186?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [noodlefighter](https://github.com/noodlefighter)**
_Thursday Dec 31, 2015 at 04:25 GMT_
_Originally opened as https://github.com/noodlefighter/LabelPlus/issues/42_

----

有人吐槽界面太乱 无从下手
试着增加step1. step2.之类的分组框

界面上增加初始文本行间距设置

**Comment by noodlefighter** [comment]
8b4fee46b2765a23efb9b18a0d6c9d17e4c39954
