### ISSUE TITLE
ps脚本导入时 应注意图像本身的“分辨率”

### ISSUE THREAD

**Issue by sgqy** [LabelPlus/PS-Script#46]
<a href="https://github.com/noodlefighter"><img src="https://avatars0.githubusercontent.com/u/5947186?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [noodlefighter](https://github.com/noodlefighter)**
_Monday Jan 25, 2016 at 09:55 GMT_
_Originally opened as https://github.com/noodlefighter/LabelPlus/issues/46_

----

![default](https://cloud.githubusercontent.com/assets/5947186/12547458/96939eec-c38b-11e5-96c2-89f337b7ea09.png)
有些图片在ps内打开后
分辨率只有1
导入的文字就会变得很小

文字的大小 和这个分辨率有关
印刷分辨率为300以上
分辨率小 字也会变小

**Comment by noodlefighter** [comment]
与脚本无关
