### ISSUE TITLE
ps脚本 - 图源后缀 - Mac下兼容性问题

### ISSUE THREAD

**Issue by sgqy** [LabelPlus/PS-Script#49]
<a href="https://github.com/kozzzx"><img src="https://avatars1.githubusercontent.com/u/9611408?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kozzzx](https://github.com/kozzzx)**
_Wednesday May 18, 2016 at 15:37 GMT_
_Originally opened as https://github.com/noodlefighter/LabelPlus/issues/49_

----

脚本内后缀显示正确，日志sourceFileType显示为.psd
需要勾选指定图源后缀名为jpg之类才能使用
![qq 20160518233353](https://cloud.githubusercontent.com/assets/9611408/15364994/262e4362-1d51-11e6-831e-592b6566c122.png)
![qq 20160518233419](https://cloud.githubusercontent.com/assets/9611408/15364995/26325e20-1d51-11e6-9cef-5190bc804e37.jpg)

**Comment by sgqy** [comment]
<a href="https://github.com/jincheng95"><img src="https://avatars3.githubusercontent.com/u/15526210?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jincheng95](https://github.com/jincheng95)**
_Wednesday Apr 12, 2017 at 16:09 GMT_

----

能否麻烦你检查一下图源路径是否正确？使用萌翻的话，一般要把图源文件夹设置成`/SQTYV72QUAL4QWDEVABQ/源图`。我看到你的log中`source`值还是root文件夹。

**Comment by noodlefighter** [comment]
最新脚本(v1.4.1)在mac ps cc2019下测试，无法重现，可能ts化后bug自己消失了
