### ISSUE TITLE
ps脚本 记住上一次设置

### ISSUE THREAD

**Issue by sgqy** [LabelPlus/PS-Script#50]
<a href="https://github.com/noodlefighter"><img src="https://avatars0.githubusercontent.com/u/5947186?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [noodlefighter](https://github.com/noodlefighter)**
_Tuesday Jun 14, 2016 at 14:20 GMT_
_Originally opened as https://github.com/noodlefighter/LabelPlus/issues/50_

----

**Comment by noodlefighter** [comment]
8d1f6e29
