### ISSUE TITLE
ps脚本 修改默认自动行距功能

### ISSUE THREAD

**Issue by sgqy** [LabelPlus/PS-Script#65]
<a href="https://github.com/noodlefighter"><img src="https://avatars0.githubusercontent.com/u/5947186?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [noodlefighter](https://github.com/noodlefighter)**
_Sunday Apr 23, 2017 at 10:38 GMT_
_Originally opened as https://github.com/noodlefighter/LabelPlus/issues/65_

----

`那个修改默认字体旁边能不能加个修改默认自动行距，现在的是175，一般都用120的，这样的少做个动作`
by 几千块

**Comment by noodlefighter** [comment]
f9ecff847df14b498386666900e7e4fe6b007a67
