### ISSUE TITLE
为使用嵌字脚本献上美好的祝福~~

### ISSUE THREAD

**Issue by yihuishou** [LabelPlus/PS-Script#73]
更好的脚本使用说明：
1. 找到`Photoshop`安装目录
2. 将嵌字脚本文件`LabelPlus_Ps_Script_ZH.jsx`复制到`Photoshop安装目录\Presets\Scripts`目录中
3. 重启Photoshop
4. 文件 -> 脚本 中即可看到嵌字脚本

示例：
![qq 20181123111813](https://user-images.githubusercontent.com/26241263/48927551-a0705900-ef11-11e8-86c9-5b7cbd7a9b9c.png)

**Comment by sgqy** [comment]
[Added](https://github.com/LabelPlus/labelplus_help/commit/ffeb87aba2f22120acf4d4759cf6aa75c27fae2d) this help manually. Thanks!
