### ISSUE TITLE
当图片名字含有']'时，会导致失败

### ISSUE THREAD

**Issue by HaiJeng** [LabelPlus/PS-Script#83]
我测试了一下，发现似乎是因为读取文件名字，在遇到‘]’便会停止的原因？
当文件名存在‘]'，lp读取txt文件时，会导致读取得到的文件名不全，无法和图片对应
如[54].jpg，log文件显示是无法找到[54文件

**Comment by noodlefighter** [comment]
已确认，确实存在这个问题。
文件格式中用到了`[]`，文件解析的实现又没有做好规避。
![image](https://user-images.githubusercontent.com/5947186/79070006-38d4cc80-7d05-11ea-9e12-11a9240cbe3c.png)

**Comment by HaiJeng** [comment]
> 已确认，确实存在这个问题。
> 文件格式中用到了`[]`，文件解析的实现又没有做好规避。
> ![image](https://user-images.githubusercontent.com/5947186/79070006-38d4cc80-7d05-11ea-9e12-11a9240cbe3c.png)

好的，期待大佬的更新ᶘ ͡°ᴥ͡°ᶅ

**Comment by noodlefighter** [comment]
已修复，感谢 @Jason23347 贡献的代码:D
