### ISSUE TITLE
当日志文件存在时抛出异常

### ISSUE THREAD

**Issue by ipid** [LabelPlus/PS-Script#97]
![错误截图](https://user-images.githubusercontent.com/5251264/105017883-4894f480-5a7f-11eb-812c-07e5f9ed9fab.png)

在使用脚本时抛出了上图中的异常，删掉 lp_ps_script.log 后问题解决。

原文件已经删掉了，所以目前暂时不知道怎么复现_(:з」∠)_

**Comment by noodlefighter** [comment]
感谢报告，现在看不出原因，之后会加上错误提示，指引用户删除日志
